---
name: Build & Deploy on GitHub Actions

on:
    push:
        branches:
            - kuza_dev

jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
        - name: Get Code from repo
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'
            
        - run: |
            cd Projet/
            go mod init main.go
            go mod tidy
            go build 
            ./main.go

            

