---

  name: Build & Deploy on GitHub Actions
  
  on:
      workflow_dispatch:
      push:
          branches:
              - kuza_dev
  env:
    ENVIRONMENT: Prod
    REGISTRY: docker.io
  
  jobs:
      build:
          runs-on: ubuntu-24.04
  
          steps:
          - name: Get Code from repo
            uses: actions/checkout@v4
  
          - name: Setup Go
            uses: actions/setup-go@v5
            with:
              go-version: '1.23'
              
          - run: |
              cd Projet/
              go mod init main.go
              go mod tidy
              go build main.go
              
          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: |
                ${{ env.REGISTRY }}/${{ vars.DOCKERHUB_USERNAME }}/goCow_Kuza83
  
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              
